language: node_js

node_js:
  - 6
  - 8
  - 10

script:
  - npm test

before_install:
  - npm -g install npm@latest-2

before_script:
  - mysql -e 'create database mysqlpromise;'
  - mysql -u travis mysqlpromise < test/fixtures/db.sql
