language: node_js

node_js:
  - 0.12
  - 4
  - 6

script:
  - npm test

before_install:
  - npm -g install npm@latest-2

before_script:
  - mysql -e 'create database mysqlpromise;'
  - mysql -u travis mysqlpromise < test/fixtures/db.sql
